enable: "etcd"
etcd:
  rootDirectory: openim
  address: [ 127.0.0.1:2379 ]
  username: root
  password: 1qaz2wsx

kubernetes:
  namespace: default

rpcService:
  chat: chat-rpc-service
  admin: admin-rpc-service
  bot: bot-rpc-service
